[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.5"
borsh = "1.5.1"
borsh-derive = "0.10.3"

[lib]
name = "identity"
crate-type = ["cdylib", "lib"]
